name: facebook message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: facebook-post-action
      uses: ReenigneArcher/facebook-post-action@v1
      with:
        page_id: ${{ secrets.FACEBOOK_PAGE_ID }}
        access_token: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        message: "Message from github actions."
        fail_on_eror: True
