name: facebook message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: facebook-post-action   
      uses: appleboy/facebook-action@master
      with:
        fb_page_token: ${{ secrets.FB_PAGE_TOKEN }}
        fb_verify_token: ${{ secrets.FB_VERIFY_TOKEN }}
        to: ${{ secrets.FB_TO }}
        args: The ${{ github.event_name }} event triggered first step.

